#!/bin/bash
#pwd
#echo "cmakeprg started"
#echo "@@@@@@@@ $*"

#~/scripts/mk.sh make $* |& tee ./makeprg.log
if [[ ! -e ./build ]] || [[ ! -d ./build ]] ; then
    echo "build does not exist or not a dir"
    exit 1
fi
cd ./build
#pwd
#make $* |& tee ./makeprg.log

TAIL_SIZE=6


if echo $1 | grep -q '\<clean\>$' ; then
    make clean |& tee ./makeprg.log

elif echo $1 | grep -q 'vim_last_3' ; then
    echo 'vim_last_3' |& tee ./makeprg.log
    make |& tail -n$TAIL_SIZE |& tee -a ./makeprg.log

else
    if ! make >& ./makeprg.tmp.log ; then
        cat ./makeprg.tmp.log |& tee ./makeprg.log

    else
        #head -n-$TAIL_SIZE ./makeprg.tmp.log |& tee ./makeprg.log
        head -n5 ./makeprg.tmp.log |& tee ./makeprg.log
    fi

fi


#make
#cat ./makeprg.log
#egrep -v '^g\+\+' < ./makeprg.log | grep -v '^make[ \[]'
exit 1
